server.port=5000
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/divine_idol_store

jwt.secret=divine_super_secret_key_change_in_production
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Create uploads dir if it doesn't exist
file.upload-dir=uploads
